### ISSUE TITLE
Error when render_script

### ISSUE THREAD

**Issue by AlexWanghaoming** [xavierpuigf/virtualhome#134]
When we run
```
comm.render_script(script_instructions1, recording=False, skip_animation=True, find_solution=True)
```
we met following error:
Traceback (most recent call last):
  File "/alpha/progprompt-vh/virtualhome/virtualhome/simulation/unity_simulator/comm_unity.py", line 92, in post_command
    resp = requests.post(self._address, json=request_dict, timeout=self.timeout_wait)
  File "/alpha/miniconda3/envs/progprompt/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/alpha/miniconda3/envs/progprompt/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/alpha/miniconda3/envs/progprompt/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/alpha/miniconda3/envs/progprompt/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/alpha/miniconda3/envs/progprompt/lib/python3.9/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=30)

The version of VirtualHome is linux_exec.v2.2.4.x86_64

**Comment by panchalutsav** [comment]
Hi, I had the similar problem, you can set the **timeout_wait** parameter when creating the communication instance and increase the limit there. By default it is set to 30s.

`comm = UnityCommunication(timeout_wait=60)`

Ref: http://virtual-home.org/documentation/master/api/interaction.html?#unity_simulator.UnityCommunication

**Comment by AlexWanghaoming** [comment]
Thanks for your solution. I have tried it and it seems to work.
