### ISSUE TITLE
How can I run the generate_snapshot.py

### ISSUE THREAD

**Issue by Ease112** [xavierpuigf/virtualhome#32]
~/dev/virtualhome/demo(master*) » python generate_snapshot.py
Traceback (most recent call last):
  File "generate_snapshot.py", line 14, in <module>
    import evolving_graph.check_programs as check_programs
  File "../simulation/evolving_graph/check_programs.py", line 11, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'

Then, I fixed the check_programs.py
import utils
-> from . import utils

But,
~/dev/virtualhome/demo(master*) » python generate_snapshot.py
Inferring preconditions...
[{'is_off': ['television', '1']}, {'plugged': ['television', '1']}, {'atreach': [['controller', '1'], ['sofa', '1']]}, {'free': ['sofa', '1']}]
Loading graph
Executing script
['[Walk] <television> (1)', '[SwitchOn] <television> (1)', '[Walk] <sofa> (1)', '[Find] <controller> (1)', '[Grab] <controller> (1)']
Traceback (most recent call last):
  File "generate_snapshot.py", line 61, in <module>
    info = check_programs.check_script(
  File "../simulation/evolving_graph/check_programs.py", line 223, in check_script
    message, executable, final_state, graph_state_list, id_mapping, info, modif_script = check_one_program(
  File "../simulation/evolving_graph/check_programs.py", line 164, in check_one_program
    helper.set_to_default_state(graph_dict, None, id_checker=lambda v: True)
  File "../simulation/evolving_graph/utils.py", line 389, in set_to_default_state
    character_id = [i["id"] for i in filter(lambda v: v["class_name"] == 'character', graph_dict["nodes"])][0]
IndexError: list index out of range

**Comment by AnyiRao** [comment]
Got similar issues

**Comment by xavierpuigf** [comment]
Thanks for pointing this out! It should be solved now. Please note that to reproduce the results from  _Synthesizing Environment-Aware Activities via Activity Sketches_ you will want to use the version one of the simulator, which you can find in https://github.com/xavierpuigf/virtualhome/releases/tag/v1.0.0
