### ISSUE TITLE
Problem for demo/generate_snapshot.py

### ISSUE THREAD

**Issue by YoheiKakiuchi** [xavierpuigf/virtualhome#42]
demo/generate_snapshot.py was failed in my environment.
Source code is current master branch and my environments were listed below.

OS: ubuntu18.04
unity_simulator: linux_exec.v2.2.4.x86_64

On the other hand, generate_video.py works well.

Here are error messages for generate_snapshot.py
Timeout may occur at comm.expand_scene...
```
virtualhome/demo# python3 generate_snapshot.py
python3 generate_snapshot.py
Inferring preconditions...
[{'is_off': ['television', '1']}, {'plugged': ['television', '1']}, {'atreach': [['controller', '1'], ['sofa', '1']]}, {'free': ['sofa', '1']}]
Loading graph
Executing script
['[Walk] <television> (1)', '[SwitchOn] <television> (1)', '[Walk] <sofa> (1)', '[Find] <controller> (1)', '[Grab] <controller> (1)']
Generating snapshots
  0% 0/6 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../simulation/unity_simulator/comm_unity.py", line 92, in post_command
    resp = requests.post(self._address, json=request_dict, timeout=self.timeout_wait)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_snapshot.py", line 74, in <module>
    messages, images = obtain_snapshots(graph_state_list, graph_input, comm)
  File "generate_snapshot.py", line 43, in obtain_snapshots
    message = comm.expand_scene(graph_state, randomize=True, random_seed=seed)
  File "../simulation/unity_simulator/comm_unity.py", line 322, in expand_scene
    'stringParams': string_params})
  File "../simulation/unity_simulator/comm_unity.py", line 98, in post_command
    raise UnityCommunicationException(str(e))
unity_simulator.comm_unity.UnityCommunicationException: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=30)
```

**Comment by YoheiKakiuchi** [comment]
demo/generate_snapshot.py may work well with unity_simulator of v2.0.0(virtualhome).
https://github.com/xavierpuigf/virtualhome/releases/download/v2.0.0/linux_exec.zip

What is the difference between v2.0.0(virtualhome) and v2.2.4(virtualhome_unity) ?

**Comment by ddevleena** [comment]
Hello, 
I get a similar error for running generate_video.py and the same type of error when trying to visualize scene number 4. I appreciate in any help in resolving! Thanks!

Specifically this is what I get for generate_video.py

Traceback (most recent call last):
  File "generate_video.py", line 9, in <module>
    comm.reset()
  File "../simulation/unity_simulator/comm_unity.py", line 224, in reset
    'intParams': [] if scene_index is None else [scene_index]})
  File "../simulation/unity_simulator/comm_unity.py", line 98, in post_command
    raise UnityCommunicationException(str(e))
unity_simulator.comm_unity.UnityCommunicationException: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b10b10630>: Failed to establish a new connection: [Errno 111] Connection refused',))


This is what I get for cell 4 in unity_demo:" comm.reset(4)" :

UnityCommunicationException: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e93d15e80>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by xavierpuigf** [comment]
> demo/generate_snapshot.py may work well with unity_simulator of v2.0.0(virtualhome).
> https://github.com/xavierpuigf/virtualhome/releases/download/v2.0.0/linux_exec.zip
> 
> What is the difference between v2.0.0(virtualhome) and v2.2.4(virtualhome_unity) ?

Hi, I only update virtualhome when there is a change in the API, the updates in v2.2.4 are bug corrections that should all be compatible with virtualhome v2.2.0. I am keeping the two repositories separate to keep the API repo small enough. I haven't tested generate_snapshot recently, I will look at what the issue could be soon. Could you try for now to make the script a bit smaller and try to execute only the first few steps?

**Comment by xavierpuigf** [comment]
> Hello,
> I get a similar error for running generate_video.py and the same type of error when trying to visualize scene number 4. I'm using v2.2.4. Using v2.0.0 didn't fix the error for me even for running generate_video.py
> 
> I appreciate in any help in resolving! Thanks!
> 
> Specifically this is what I get for generate_video.py
> 
> Traceback (most recent call last):
> File "generate_video.py", line 9, in
> comm.reset()
> File "../simulation/unity_simulator/comm_unity.py", line 224, in reset
> 'intParams': [] if scene_index is None else [scene_index]})
> File "../simulation/unity_simulator/comm_unity.py", line 98, in post_command
> raise UnityCommunicationException(str(e))
> unity_simulator.comm_unity.UnityCommunicationException: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b10b10630>: Failed to establish a new connection: [Errno 111] Connection refused',))
> 
> This is what I get for cell 4 in unity_demo:" comm.reset(4)" :
> 
> UnityCommunicationException: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e93d15e80>: Failed to establish a new connection: [Errno 111] Connection refused',))

Hi @ddevleena , from what you mention, it seems like the demo fails the first step that you execute with Unity. This is most likely because the unity simulator is just not running. Notice that the default mode is manual, this means you need to open the simulator first. Have you made sure the simulator is running before running that cell in the demo?

**Comment by YoheiKakiuchi** [comment]
Here is a small script for testing.
This should be run at virtualhome/demo directory.

```
import sys
import random

sys.path.append('../simulation')
from unity_simulator.comm_unity import UnityCommunication

comm = UnityCommunication()

####                                                                                                                                           
print('com.reset')
comm.reset(4)

#print('comm.add_character')                                                                                                                   
#comm.add_character('Chars/Female4', initial_room='bedroom')                                                                                   

print('comm.environment_graph')
_, graph = comm.environment_graph()

print('comm.expand_scene')
suc, mesg = comm.expand_scene(graph)

print('Done first try')

####                                                                                                                                           
print('com.reset')
comm.reset(4)

print('comm.add_character')
comm.add_character('Chars/Female4', initial_room='bedroom')

print('comm.environment_graph')
_, graph = comm.environment_graph()

print('comm.expand_scene')
suc, mesg = comm.expand_scene(graph)

print('Done second try')
```


With v2.0.0(virtualhome), all scripts may success.
```
com.reset
comm.environment_graph
comm.expand_scene
Done first try
com.reset
comm.add_character
comm.environment_graph
comm.expand_scene
Done second try
```


With v2.2.4(virtualhome_unity), scripts may fail at the last comm.expand.
Difference from the success case is adding a character before environment_graph and expand_scene.
```
com.reset
comm.environment_graph
comm.expand_scene
Done first try
com.reset
comm.add_character
comm.environment_graph
comm.expand_scene
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../simulation/unity_simulator/comm_unity.py", line 92, in post_command
    resp = requests.post(self._address, json=request_dict, timeout=self.timeout_wait)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug_test.py", line 45, in <module>
    suc, mesg = comm.expand_scene(graph)
  File "../simulation/unity_simulator/comm_unity.py", line 321, in expand_scene
    'stringParams': string_params})
  File "../simulation/unity_simulator/comm_unity.py", line 97, in post_command
    raise UnityCommunicationException(str(e))
unity_simulator.comm_unity.UnityCommunicationException: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=30)
```

**Comment by ToddBear** [comment]
Hi YoheiKakiuchi, i met the same problem.
I found that if remove the code below, the problem can be solved.
` comm.add_character()`

**Comment by ToddBear** [comment]
Hi @YoheiKakiuchi  ! I met the same problem when adding a character. Did you fix the problems occurred in v2.2.4?

**Comment by kswain98** [comment]
Hi @ToddBear! I'll take a look and see if the issue occurs on the new version.

**Comment by ToddBear** [comment]
Hi @kswain98 ! I tested on the latest version, and find that the problems also occurred when there is "add_character" before "expand_scene()".
```
        comm.reset(0)
        comm.add_character()
        message = comm.expand_scene(graph_state, randomize=False, random_seed=seed)
```

**Comment by kswain98** [comment]
Thanks for letting me know @ToddBear! I will also take a look at this and get back to you with a fix!

**Comment by Xianqi-Zhang** [comment]
> Hi @kswain98 ! I tested on the latest version, and find that the problems also occurred when there is "add_character()" before "expand_scene()".
> 
> ```
>         comm.reset(0)
>         comm.add_character()
>         message = comm.expand_scene(graph_state, randomize=False, random_seed=seed)
> ```

Same Error with 2.3.0, Ubuntu 18.0.4

**Comment by kswain98** [comment]
> > Hi @kswain98 ! I tested on the latest version, and find that the problems also occurred when there is "add_character()" before "expand_scene()".
> 
> > 
> 
> > ```
> 
> >         comm.reset(0)
> 
> >         comm.add_character()
> 
> >         message = comm.expand_scene(graph_state, randomize=False, random_seed=seed)
> 
> > ```
> 
> 
> 
> Same Error with 2.3.0, Ubuntu 18.0.4

Hey! Sorry for the late response! Will take a look at this right away!

**Comment by zhangliyun9120** [comment]
Hi guys, have you resolved this problem? I also got the same error when I use v2.3.0 virtualhome_unity in other codes: https://github.com/UMass-Foundation-Model/Co-LLM-Agents/issues/1.

If you fix the problem, please share the solution ASAP, Thx.

**Comment by kswain55** [comment]
@Xianqi-Zhang @zhangliyun9120 Apologies for the extremely late response! I haven't had much time to fix the bugs in VirtualHome for the past few months but I'll take a look at all of this soon.

**Comment by lmz123321** [comment]
I fixed a similar timeout issue [here](https://github.com/xavierpuigf/virtualhome_unity/issues/23) by replacing the ```yield return new WaitForEndOfFrame();``` in csharp functions to ```yield return null```.

According to this [blog](https://forum.unity.com/threads/do-not-use-waitforendofframe.883648/), using ```yield return new WaitForEndOfFrame();```  in batch mode can trigger a timeout error.

Hope this helps ^_^ @Xianqi-Zhang @zhangliyun9120

**Comment by Arpitrf** [comment]
@lmz123321 did you need to purchase the third-party assets to make this edit and regenerate a new executable? Is there a way to sidestep the purchase?

**Comment by lmz123321** [comment]
@Arpitrf I believe this error only happens when you use Unity Hub to run virtual-home (in order to make some custom modiftications to the environment).

If you just want to use the environment, you can use the official [docker](https://github.com/xavierpuigf/virtualhome/tree/master/docker), which does not need compilation nor third-party assets.

Hope this help.

**Comment by Arpitrf** [comment]
@lmz123321 with docker, I am facing this error - https://github.com/xavierpuigf/virtualhome/issues/21. There is no solution yet provided in that GitHub issue. Do you have any idea what could be going wrong?

**Comment by lmz123321** [comment]
@Arpitrf I am not sure what's going wrong. 

But you can fix this by deleting the run_sim.sh line in Dockerfile, rebuild the docker image, and then run the run_sim.sh manually in the container.

**Comment by Arpitrf** [comment]
Thanks a lot, that helped! But, now I am facing this issue where I get the timeout error as follows - 
<img width="1158" alt="Screenshot 2024-03-22 at 10 44 04 PM" src="https://github.com/xavierpuigf/virtualhome/assets/14124093/d23190f1-dbeb-4daa-a925-150889f688ba">
<img width="742" alt="Screenshot 2024-03-22 at 10 45 15 PM" src="https://github.com/xavierpuigf/virtualhome/assets/14124093/d3acc08e-3dd7-4d98-b262-727ed01abced">
