### ISSUE TITLE
 "socket.timeout: timed out" when attempting to launch "generate_snapshot.py."

### ISSUE THREAD

**Issue by Xial-kotori** [xavierpuigf/virtualhome#95]
OS: Windows 10 Pro 22H2
unity_simulator: windows_exec.v2.3.0
Python: 3.8

Both `generate_video.py` and `generate_snapshot.py` will cause similar error message.
I launched VirtualHome.exe and then run command `python .\generate_snapshot.py`. The error message is:

```
Inferring preconditions...
[{'is_off': ['television', '1']}, {'plugged': ['television', '1']}, {'atreach': [['controller', '1'], ['sofa', '1']]}, {'free': ['sofa', '1']}]
Loading graph
Executing script
['[Walk] <television> (1)', '[SwitchOn] <television> (1)', '[Walk] <sofa> (1)', '[Find] <controller> (1)', '[Grab] <controller> (1)']
Generating snapshots
  0%|                                                                                            | 0/6 [00:00<?, ?it/s]Traceback (most recent call last):
  File "***\miniconda3\envs\virtualhome\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "***\miniconda3\envs\virtualhome\lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "***\miniconda3\envs\virtualhome\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "***\miniconda3\envs\virtualhome\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "***\miniconda3\envs\virtualhome\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "***\miniconda3\envs\virtualhome\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "***\miniconda3\envs\virtualhome\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "***\miniconda3\envs\virtualhome\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "***\miniconda3\envs\virtualhome\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "***\miniconda3\envs\virtualhome\lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "***\miniconda3\envs\virtualhome\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "***\miniconda3\envs\virtualhome\lib\site-packages\urllib3\connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "***\miniconda3\envs\virtualhome\lib\site-packages\urllib3\connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "***\virtualhome\src\virtualhome\demo\../simulation\unity_simulator\comm_unity.py", line 92, in post_command
    resp = requests.post(self._address, json=request_dict, timeout=self.timeout_wait)
  File "***\miniconda3\envs\virtualhome\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "***\miniconda3\envs\virtualhome\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "***\miniconda3\envs\virtualhome\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "***\miniconda3\envs\virtualhome\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "***\miniconda3\envs\virtualhome\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\generate_snapshot.py", line 74, in <module>
    messages, images = obtain_snapshots(graph_state_list, graph_input, comm)
  File ".\generate_snapshot.py", line 43, in obtain_snapshots
    message = comm.expand_scene(graph_state, randomize=True, random_seed=seed)
  File "***\virtualhome\src\virtualhome\demo\../simulation\unity_simulator\comm_unity.py", line 394, in expand_scene
    response = self.post_command({'id': str(time.time()), 'action': 'expand_scene',
  File "***\virtualhome\src\virtualhome\demo\../simulation\unity_simulator\comm_unity.py", line 98, in post_command
    raise UnityCommunicationException(str(e))
unity_simulator.comm_unity.UnityCommunicationException: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=30)
```

**Comment by HuiHuiSun** [comment]
Hello!
I'm meeting the same error. Did you solve it?

**Comment by Xial-kotori** [comment]
Sorry, I haven't found a solution yet.

**Comment by Arpitrf** [comment]
I am facing the same issue! For me, the generate_video.py works but I get this error when running generate_snapshot.py

**Comment by harshg99** [comment]
i am facing the same issue here too on mac
